language: csharp
mono: none
dotnet: 3.1
solution: ICT3101_Calculator.sln
      
script:
  - dotnet restore #this will restore are settings and get all our NuGet packages
  - dotnet test #this will run all our tests
